import { NextResponse } from "next/server";
export const dynamic = "force-dynamic";
type Job = {
  company: string;
  location: string;
  position: string;
  status: "active";
};
const positions = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Software Engineer",
  "Mobile App Developer",
  "UI/UX Designer",
  "Product Designer",
  "Product Manager",
  "Project Manager",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "Cybersecurity Analyst",
  "Cloud Engineer",
  "DevOps Engineer",
  "QA Engineer",
  "Technical Support Specialist",
  "Customer Success Specialist",
  "Digital Marketing Specialist",
  "Content Strategist",
  "Social Media Manager",
  "SEO Specialist",
  "Copywriter",
  "Graphic Designer",
  "Video Editor",
  "Technical Writer",
  "Business Analyst",
  "Financial Analyst",
  "Operations Coordinator",
  "Virtual Assistant",
  "Administrative Assistant",
  "Recruitment Specialist",
  "Human Resources Specialist",
  "Sales Representative",
  "Account Manager",
  "Business Development Executive",
  "Customer Service Representative",
  "Research Assistant",
  "Market Research Analyst",
  "E-commerce Specialist",
  "Community Manager",
  "Email Marketing Specialist",
  "WordPress Developer",
  "Shopify Specialist",
  "Data Entry Specialist",
  "Transcription Specialist",
  "Online Tutor",
  "Content Moderator",
  "Remote Operations Specialist",
];
const countryData: Record<
  string,
  {
    name: string;
    companies: string[];
  }
> = {
  "united-states": {
    name: "United States",
    companies: [
      "Northstar Digital",
      "BrightForge Labs",
      "BluePeak Systems",
      "SummitArc Technologies",
      "Vertex Cloudworks",
      "Everline Digital",
      "Redwood Nexus",
      "CrestPoint Labs",
      "SilverOak Systems",
      "HorizonStack",
      "Westbridge Digital",
      "Pioneer Grid",
      "ClearPath Technologies",
      "Skyward Labs",
      "Oakline Solutions",
      "AtlasCore",
      "BrightRiver Systems",
      "NorthBridge Works",
      "CobaltPeak",
      "UrbanForge Digital",
      "Stonebridge Labs",
      "NovaTrail Technologies",
      "ElevateGrid",
      "PrimeOrbit",
      "CloudHarbor",
      "BlueRiver Works",
      "ApexField Digital",
      "Ironwood Technologies",
      "LumenPath",
      "VenturePeak",
      "CoreVista",
      "BrightStone Labs",
      "NorthPoint Digital",
      "EverPeak Systems",
      "CedarWave",
      "OrbitLane",
      "WestNova Technologies",
      "SummitBridge",
      "ClearSky Digital",
      "RedPeak Labs",
      "HarborPoint Systems",
      "OakVista",
      "PioneerWave",
      "BlueCrest Digital",
      "Nexora Labs",
      "SkylineForge",
      "AtlasWave",
      "Crestline Technologies",
      "UrbanPeak Systems",
      "Northshore Digital",
    ],
  },
  canada: {
    name: "Canada",
    companies: [
      "MapleCore Technologies",
      "Northern Edge Labs",
      "Pinebridge Digital",
      "TrueNorth Systems",
      "AuroraStack",
      "Lakefront Technologies",
      "CedarPeak Digital",
      "PolarBridge Labs",
      "MapleWave Systems",
      "Northfield Digital",
      "Evergreen Nexus",
      "GranitePath Technologies",
      "Frostline Labs",
      "RedMaple Systems",
      "HarborNorth Digital",
      "SummitMaple",
      "BluePine Technologies",
      "CrownPeak Labs",
      "Northern Horizon",
      "OakLake Digital",
      "MapleRiver Systems",
      "PolarVista",
      "CedarNorth Technologies",
      "AuroraPoint",
      "GreatNorth Digital",
      "SilverMaple Labs",
      "PineCrest Systems",
      "LakeNova Technologies",
      "NorthStar Maple",
      "EverPeak Canada",
      "MapleBridge Digital",
      "FrostPeak Systems",
      "NorthernGrid",
      "CedarWave Canada",
      "AuroraForge",
      "GraniteNorth Digital",
      "PolarPath Technologies",
      "MapleHarbor Labs",
      "BlueNorth Systems",
      "LakePoint Digital",
      "CrownMaple Technologies",
      "PineNova",
      "NorthernCrest Labs",
      "EvergreenPeak",
      "MapleVista Systems",
      "FrostBridge Digital",
      "AuroraLane",
      "GreatPine Technologies",
      "NorthCedar Labs",
      "MapleSummit Digital",
    ],
  },
  "united-kingdom": {
    name: "United Kingdom",
    companies: [
      "Britannia Digital",
      "LondonForge Labs",
      "CrownStack Technologies",
      "Westminster Digital",
      "ThamesPoint Systems",
      "RoyalOak Labs",
      "Northbridge UK",
      "Brighton Nexus",
      "Yorkshire Digital",
      "CambridgeCore",
      "BristolWave Technologies",
      "Manchester Grid",
      "Edinburgh Peak",
      "OxfordLane Digital",
      "KentBridge Systems",
      "Liverpool Labs",
      "Cotswold Technologies",
      "Birmingham Nexus",
      "Lancaster Digital",
      "SomersetStack",
      "LeedsPoint Systems",
      "Cornwall Digital",
      "DerbyForge",
      "Sussex Labs",
      "Windsor Technologies",
      "SheffieldCore",
      "Nottingham Digital",
      "DevonBridge",
      "Glasgow Nexus",
      "Cheshire Systems",
      "BrightCrown Labs",
      "ThamesForge",
      "Northern Crown Digital",
      "Westfield Technologies",
      "OxfordPeak",
      "BristolCore Systems",
      "YorkBridge Digital",
      "Camden Labs",
      "KentPeak Technologies",
      "RoyalBridge Systems",
      "ManchesterWave",
      "EdinburghCore",
      "LondonNorth Digital",
      "CrownPoint Labs",
      "BrightonStack",
      "Wessex Technologies",
      "Midlands Digital",
      "ThamesNova",
      "BritCore Systems",
      "Westminster Labs",
    ],
  },
  australia: {
    name: "Australia",
    companies: [
      "SouthernCross Digital",
      "AussieCore Technologies",
      "Outback Labs",
      "SydneyForge",
      "Melbourne Nexus",
      "HarborWave Systems",
      "CoralPeak Digital",
      "Tasman Technologies",
      "BlueGum Labs",
      "SunriseStack",
      "PacificPoint Systems",
      "GoldenCoast Digital",
      "Eucalyptus Technologies",
      "BrisbaneCore",
      "PerthBridge Labs",
      "Adelaide Digital",
      "Canberra Nexus",
      "DarwinPeak",
      "CoastalForge Systems",
      "SouthernGrid",
      "HarborPoint Australia",
      "OutbackWave",
      "CoralBridge Technologies",
      "BlueSky Digital",
      "TasmanCore",
      "SydneyPeak Labs",
      "MelbournePoint Systems",
      "SunCoast Technologies",
      "AussieNova Digital",
      "PacificForge",
      "EucalyptusCore",
      "SouthernVista",
      "BrisbaneWave",
      "PerthNexus",
      "AdelaideForge",
      "CanberraPeak Digital",
      "TasmanPoint Systems",
      "CoralNova Labs",
      "HarborCore Australia",
      "OutbackBridge",
      "BlueGum Technologies",
      "SouthernPeak Digital",
      "SydneyNorth Labs",
      "MelbourneWave Systems",
      "PacificCrest",
      "SunriseCore Technologies",
      "AussieBridge Digital",
      "CoastalNexus",
      "GoldenPeak Systems",
      "SouthernHarbor Labs",
    ],
  },
  "new-zealand": {
    name: "New Zealand",
    companies: [
      "KiwiCore Digital",
      "SouthernPeak Technologies",
      "Aotearoa Labs",
      "PacificFern Systems",
      "HarborPoint NZ",
      "SilverFern Digital",
      "AlpineStack",
      "TasmanCore Technologies",
      "KiwiBridge Labs",
      "Auckland Nexus",
      "Wellington Digital",
      "Christchurch Forge",
      "Queenstown Systems",
      "Rotorua Technologies",
      "Dunedin Digital",
      "NorthIsland Labs",
      "SouthIsland Systems",
      "PacificPeak",
      "FernWave Technologies",
      "AlpinePoint Digital",
      "KiwiVista Labs",
      "HarborCore",
      "Aotearoa Nexus",
      "TasmanBridge",
      "SouthernFern Digital",
      "BlueFern Technologies",
      "PacificCore Systems",
      "KiwiForge",
      "AlpineWave Digital",
      "WellingtonPeak",
      "AucklandCore Technologies",
      "Christchurch Nexus",
      "SouthernHarbor Labs",
      "FernPoint Systems",
      "TasmanPeak Digital",
      "KiwiNorth Technologies",
      "SilverPeak Labs",
      "PacificBridge",
      "Aotearoa Digital",
      "AlpineCrest Systems",
      "HarborFern Technologies",
      "KiwiNova Digital",
      "SouthernCore Labs",
      "WellingtonWave",
      "AucklandPoint Systems",
      "PacificVista Technologies",
      "FernCrest Digital",
      "TasmanNova Labs",
      "KiwiSummit Systems",
      "SouthernBridge Digital",
      "Aotearoa Peak",
    ],
  },
  china: {
    name: "China",
    companies: [
      "DragonPeak Technologies",
      "JadeBridge Digital",
      "SilkRoad Labs",
      "Shanghai Nexus",
      "BeijingCore Systems",
      "PearlRiver Digital",
      "GoldenDragon Technologies",
      "EastWind Labs",
      "RedLotus Systems",
      "GreatWall Digital",
      "JadeCore Technologies",
      "SinoPeak Labs",
      "PandaBridge Systems",
      "ShanghaiForge",
      "BeijingWave Digital",
      "PearlPoint Technologies",
      "DragonVista Labs",
      "SilkCore Systems",
      "EasternPeak Digital",
      "JadeNova Technologies",
      "RedRiver Labs",
      "GoldenPeak Systems",
      "ChinaBridge Digital",
      "PandaCore Technologies",
      "EastStar Labs",
      "DragonWave Systems",
      "JadePoint Digital",
      "SilkBridge Technologies",
      "PearlNova Labs",
      "GreatEast Systems",
      "BeijingPeak Digital",
      "ShanghaiCore Technologies",
      "SinoBridge Labs",
      "DragonCrest Systems",
      "JadeHarbor Digital",
      "EastWind Technologies",
      "PandaPeak Labs",
      "GoldenBridge Systems",
      "SilkNova Digital",
      "PearlCore Technologies",
      "RedDragon Labs",
      "EasternForge Systems",
      "JadeSummit Digital",
      "ChinaPeak Technologies",
      "DragonPoint Labs",
      "SinoCore Systems",
      "PandaWave Digital",
      "GoldenLotus Technologies",
      "SilkPeak Labs",
      "PearlBridge Systems",
    ],
  },
  nigeria: {
    name: "Nigeria",
    companies: [
      "Lagos Horizon",
      "NaijaTech Works",
      "GreenCity Digital",
      "AfriCore Technologies",
      "NexaLagos Labs",
      "KoraBridge Systems",
      "Savanna Digital",
      "Coastline Technologies",
      "AfriPeak Labs",
      "LagosForge",
      "NaijaCore Systems",
      "WestAfrica Digital",
      "PalmTree Technologies",
      "Nigerian Nexus",
      "LagosWave Labs",
      "AfriBridge Digital",
      "KoraTech Systems",
      "SavannaCore",
      "LagosPoint Technologies",
      "Atlantic Digital",
      "NaijaNova Labs",
      "AfriVista Systems",
      "GreenPeak Technologies",
      "LagosCore Digital",
      "WestBridge Labs",
      "KoraPeak Systems",
      "SavannaWave Technologies",
      "AfriNova Digital",
      "LagosNexus Labs",
      "PalmCore Systems",
      "NaijaBridge Technologies",
      "CoastPeak Digital",
      "AfriForge Labs",
      "LagosSummit Systems",
      "GreenBridge Technologies",
      "WestAfrica Nexus",
      "KoraPoint Digital",
      "SavannaPeak Labs",
      "NaijaWave Systems",
      "LagosVista Technologies",
      "AfriHarbor Digital",
      "PalmPeak Labs",
      "CoastCore Systems",
      "NaijaPoint Technologies",
      "LagosNova Digital",
      "AfriSummit Labs",
      "KoraWave Systems",
      "SavannaBridge Technologies",
      "GreenCore Digital",
      "LagosPeak Labs",
    ],
  },
};
function shuffleJobs(jobs: Job[]) {
  const shuffled = [...jobs];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const randomIndex = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[randomIndex]] = [
      shuffled[randomIndex],
      shuffled[i],
    ];
  }
  return shuffled;
}
export async function GET(
  request: Request,
  { params }: { params: Promise<{ country: string }> },
) {
  const { country } = await params;
  const countrySlug = decodeURIComponent(country).toLowerCase();
  const selectedCountry = countryData[countrySlug];
  if (!selectedCountry) {
    return NextResponse.json(
      {
        error: "Country not supported",
      },
      {
        status: 404,
      },
    );
  }
  /*
   * Each country has 50 companies and 50 unique positions.
   * We pair them together to create the listings.
   */
  const allJobs: Job[] = selectedCountry.companies.map(
    (company, index) => ({
      company,
      location: selectedCountry.name,
      position: positions[index],
      status: "active",
    }),
  );
  /*
   * Randomize all 50 listings and return only 30.
   */
  const selectedJobs = shuffleJobs(allJobs).slice(0, 30);
  /*
   * Shuffle the selected 30 one more time so the
   * display order is also randomized.
   */
  const finalJobs = shuffleJobs(selectedJobs);
  return NextResponse.json(
    {
      country: selectedCountry.name,
      total: allJobs.length,
      displayed: finalJobs.length,
      jobs: finalJobs,
    },
    {
      headers: {
        "Cache-Control": "no-store, max-age=0",
      },
    },
  );
}