import { NextResponse } from "next/server";
type DataEntryJob = {
  company: string;
  location: string;
  position: string;
  status: "active";
};
type CountryData = {
  country: string;
  companies: string[];
  positions: string[];
};
/*
 * Demo/sample listings.
 * These company names are hardcoded placeholders for the platform.
 * They should not be presented as verified real vacancies.
 */
const countries: CountryData[] = [
  {
    country: "United States",
    companies: [
      "NorthBridge Data Solutions",
      "ClearPath Operations",
      "BluePeak Administrative",
      "Summit Data Services",
      "Everline Business Support",
      "BrightDesk Solutions",
      "PrimeCore Operations",
      "Westfield Data Group",
      "Oakstone Digital Services",
      "Silverline Administration",
      "MetroPoint Data Services",
      "Redwood Business Solutions",
      "Pioneer Desk Operations",
      "GrandView Data Group",
      "Lakefront Administrative",
      "CedarWorks Services",
      "Atlas Data Processing",
      "Horizon Desk Solutions",
      "Liberty Data Services",
      "Vertex Administrative Group",
      "CrownPoint Operations",
      "NorthStar Records Services",
      "UrbanCore Data Solutions",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Data Entry Associate",
      "Online Data Entry Specialist",
      "Records Data Clerk",
      "Database Entry Assistant",
      "Administrative Data Clerk",
      "Data Verification Specialist",
      "Digital Records Assistant",
      "Data Input Specialist",
      "Information Processing Clerk",
      "Data Management Assistant",
      "Document Data Specialist",
      "Data Quality Assistant",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Entry-Level Data Specialist",
      "Customer Data Clerk",
      "Data Administration Assistant",
      "Digital Data Entry Clerk",
      "Data Capture Specialist",
      "Back Office Data Assistant",
    ],
  },
  {
    country: "United Kingdom",
    companies: [
      "Britannia Data Services",
      "London Desk Solutions",
      "Crown Data Operations",
      "Westminster Business Support",
      "Oakfield Records",
      "Thames Data Group",
      "Northern Desk Services",
      "Redbridge Administration",
      "Cambridge Data Solutions",
      "Bristol Operations Group",
      "Yorkshire Data Services",
      "Brighton Records Support",
      "Manchester Data Operations",
      "Kingston Business Services",
      "Oxford Data Management",
      "Lancashire Desk Solutions",
      "Birmingham Data Group",
      "Kent Administrative Services",
      "Leeds Data Processing",
      "Windsor Records Solutions",
      "Sheffield Business Support",
      "Liverpool Data Services",
      "Nottingham Data Operations",
    ],
    positions: [
      "Data Entry Clerk",
      "Remote Data Entry Assistant",
      "Data Processing Clerk",
      "Administrative Data Assistant",
      "Records Entry Specialist",
      "Online Data Clerk",
      "Data Verification Assistant",
      "Document Processing Clerk",
      "Database Assistant",
      "Data Input Clerk",
      "Information Entry Assistant",
      "Data Quality Clerk",
      "Digital Records Clerk",
      "Back Office Data Assistant",
      "Data Management Clerk",
      "Remote Records Assistant",
      "Data Capture Clerk",
      "Business Data Assistant",
      "Customer Records Clerk",
      "Data Administration Clerk",
      "Entry-Level Data Clerk",
      "Data Operations Clerk",
      "Document Data Assistant",
    ],
  },
  {
    country: "Australia",
    companies: [
      "Southern Cross Data",
      "Aussie Desk Solutions",
      "Coral Coast Operations",
      "BlueGum Data Services",
      "Harbour Data Group",
      "Outback Business Support",
      "Sunrise Records Solutions",
      "Pacific Desk Operations",
      "Melbourne Data Services",
      "Sydney Data Group",
      "Brisbane Administrative",
      "Perth Data Solutions",
      "Adelaide Records Services",
      "Gold Coast Data Operations",
      "Tasman Business Support",
      "Eucalyptus Data Group",
      "Southern Desk Services",
      "Coastal Data Management",
      "RedEarth Operations",
      "BlueWater Records",
      "Kangaroo Data Solutions",
      "HarbourPoint Administration",
      "Sunland Data Services",
    ],
    positions: [
      "Data Entry Specialist",
      "Data Processing Assistant",
      "Remote Data Clerk",
      "Records Data Assistant",
      "Online Data Entry Clerk",
      "Administrative Data Specialist",
      "Data Verification Clerk",
      "Database Entry Assistant",
      "Digital Records Specialist",
      "Data Input Assistant",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Entry Specialist",
      "Data Quality Clerk",
      "Remote Records Specialist",
      "Data Operations Assistant",
      "Customer Data Assistant",
      "Data Administration Specialist",
      "Data Capture Assistant",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Document Processing Assistant",
      "Back Office Data Clerk",
    ],
  },
  {
    country: "New Zealand",
    companies: [
      "Kiwi Data Services",
      "Southern Alps Operations",
      "Pacific Desk Group",
      "Aotearoa Data Solutions",
      "Harbour Records Services",
      "SilverFern Administration",
      "Tasman Data Group",
      "Greenland Business Support",
      "Wellington Data Services",
      "Auckland Records Solutions",
      "Christchurch Data Operations",
      "Dunedin Desk Services",
      "Rotorua Data Group",
      "Hamilton Business Support",
      "Nelson Data Solutions",
      "Queenstown Records Services",
      "Koru Data Operations",
      "IslandDesk Solutions",
      "Pacific Records Group",
      "FernTree Data Services",
      "Southern Harbour Operations",
      "BlueLake Data Solutions",
    ],
    positions: [
      "Data Entry Clerk",
      "Remote Data Assistant",
      "Data Processing Specialist",
      "Records Entry Clerk",
      "Online Data Specialist",
      "Administrative Data Clerk",
      "Data Verification Specialist",
      "Database Assistant",
      "Digital Records Assistant",
      "Data Input Clerk",
      "Information Data Assistant",
      "Data Management Specialist",
      "Document Data Clerk",
      "Data Quality Assistant",
      "Remote Records Clerk",
      "Data Operations Specialist",
      "Customer Data Clerk",
      "Data Administration Assistant",
      "Data Capture Specialist",
      "Business Records Assistant",
      "Entry-Level Data Clerk",
      "Back Office Data Assistant",
    ],
  },
  {
    country: "Denmark",
    companies: [
      "Nordic Data Works",
      "Copenhagen Data Services",
      "Danish Desk Solutions",
      "Nordic Records Group",
      "BlueHarbour Operations",
      "Scandi Data Support",
      "Aarhus Data Solutions",
      "Odense Records Services",
      "Aalborg Data Group",
      "Viking Business Support",
      "NordPoint Administration",
      "Crown Nordic Data",
      "Baltic Desk Services",
      "Fjord Data Operations",
      "Nordic Digital Records",
      "Copenhagen Operations Group",
      "Danish Data Management",
      "ScandiDesk Solutions",
      "Northern Records Services",
      "Nordic Entry Group",
      "FjordPoint Data",
      "Danish Business Records",
      "Nordic Core Operations",
    ],
    positions: [
      "Data Entry Specialist",
      "Data Processing Clerk",
      "Remote Data Assistant",
      "Records Data Clerk",
      "Administrative Data Specialist",
      "Online Data Entry Assistant",
      "Data Verification Clerk",
      "Database Data Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Clerk",
      "Data Management Assistant",
      "Document Data Specialist",
      "Data Quality Clerk",
      "Remote Records Assistant",
      "Data Operations Clerk",
      "Customer Data Specialist",
      "Data Administration Clerk",
      "Data Capture Assistant",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Back Office Data Assistant",
      "Document Processing Specialist",
    ],
  },
  {
    country: "France",
    companies: [
      "Paris Data Services",
      "Hexagon Data Solutions",
      "France Desk Operations",
      "Lumiere Records Group",
      "Marseille Data Support",
      "Lyon Data Services",
      "Bordeaux Records Solutions",
      "Nice Business Data",
      "Versailles Data Operations",
      "Rhone Data Group",
      "Seine Administrative",
      "FrenchCore Data Services",
      "Azur Records Group",
      "Atlantic Data Solutions",
      "Montpellier Desk Services",
      "Nantes Data Operations",
      "Toulouse Records Support",
      "Provence Data Group",
      "French Data Management",
      "ParisPoint Operations",
      "Eiffel Data Services",
      "Loire Business Support",
      "HexaDesk Solutions",
    ],
    positions: [
      "Data Entry Clerk",
      "Data Processing Assistant",
      "Remote Data Entry Specialist",
      "Records Data Assistant",
      "Online Data Clerk",
      "Administrative Data Specialist",
      "Data Verification Assistant",
      "Database Entry Clerk",
      "Digital Records Specialist",
      "Data Input Assistant",
      "Information Processing Specialist",
      "Data Management Clerk",
      "Document Entry Assistant",
      "Data Quality Specialist",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Customer Data Clerk",
      "Data Administration Specialist",
      "Data Capture Clerk",
      "Business Data Assistant",
      "Entry-Level Data Clerk",
      "Back Office Data Specialist",
      "Document Processing Clerk",
    ],
  },
  {
    country: "Canada",
    companies: [
      "MapleCore Data Services",
      "Northern Data Solutions",
      "Canadian Desk Operations",
      "TrueNorth Records Group",
      "MapleLeaf Business Support",
      "Toronto Data Services",
      "Vancouver Data Solutions",
      "Montreal Records Group",
      "Calgary Data Operations",
      "Ottawa Desk Services",
      "Edmonton Data Support",
      "Quebec Data Solutions",
      "Prairie Data Group",
      "Atlantic Records Services",
      "Rocky Mountain Data",
      "Great Lakes Operations",
      "MaplePoint Administration",
      "Northern Star Data",
      "Cedar Canada Services",
      "Polar Data Operations",
      "Frontier Records Group",
      "Canadian Data Management",
      "Aurora Desk Solutions",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Specialist",
      "Online Data Entry Assistant",
      "Administrative Data Clerk",
      "Data Verification Specialist",
      "Database Entry Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Data Assistant",
      "Data Quality Specialist",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Customer Data Specialist",
      "Data Administration Clerk",
      "Data Capture Specialist",
      "Business Data Assistant",
      "Entry-Level Data Clerk",
      "Back Office Data Assistant",
      "Document Processing Specialist",
    ],
  },
  {
    country: "Kuwait",
    companies: [
      "Gulf Data Services",
      "Kuwait Desk Solutions",
      "Desert Data Operations",
      "Pearl Records Group",
      "Kuwait Business Support",
      "GulfCore Data Services",
      "Capital Data Solutions",
      "Kuwait Records Operations",
      "Arabian Desk Group",
      "GulfPoint Administration",
      "Kuwait Digital Records",
      "Desert Data Management",
      "Pearl Data Solutions",
      "Kuwait Operations Group",
      "Gulf Records Services",
      "Falcon Data Operations",
      "Kuwait Data Support",
      "GulfDesk Administration",
      "Arabian Data Group",
      "Capital Records Services",
      "Kuwait DataWorks",
      "DesertPoint Operations",
    ],
    positions: [
      "Data Entry Clerk",
      "Data Processing Specialist",
      "Remote Data Assistant",
      "Records Data Clerk",
      "Administrative Data Assistant",
      "Online Data Entry Specialist",
      "Data Verification Clerk",
      "Database Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Data Specialist",
      "Data Quality Assistant",
      "Remote Records Specialist",
      "Data Operations Clerk",
      "Customer Data Assistant",
      "Data Administration Specialist",
      "Data Capture Clerk",
      "Business Data Specialist",
      "Entry-Level Data Assistant",
      "Back Office Data Clerk",
    ],
  },
  {
    country: "Germany",
    companies: [
      "German DataWorks",
      "Berlin Data Services",
      "Rhine Data Solutions",
      "Munich Records Group",
      "Frankfurt Desk Operations",
      "Bavaria Data Support",
      "Hamburg Data Services",
      "Cologne Records Solutions",
      "Stuttgart Data Operations",
      "Leipzig Desk Group",
      "Dresden Data Services",
      "GermanCore Administration",
      "BlackForest Data Group",
      "RhinePoint Records",
      "Berlin Business Data",
      "Nordic German Operations",
      "Alpine Data Solutions",
      "German Records Management",
      "Central Data Services",
      "Munich Data Operations",
      "Frankfurt Data Group",
      "EuroDesk Germany",
      "GermanPoint Solutions",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Clerk",
      "Online Data Specialist",
      "Administrative Data Assistant",
      "Data Verification Specialist",
      "Database Entry Clerk",
      "Digital Records Assistant",
      "Data Input Clerk",
      "Information Processing Specialist",
      "Data Management Assistant",
      "Document Data Clerk",
      "Data Quality Specialist",
      "Remote Records Assistant",
      "Data Operations Specialist",
      "Customer Data Clerk",
      "Data Administration Assistant",
      "Data Capture Specialist",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Back Office Data Assistant",
      "Document Processing Clerk",
    ],
  },
  {
    country: "Portugal",
    companies: [
      "Lisbon Data Services",
      "Atlantic Data Solutions",
      "Portugal Desk Group",
      "Porto Records Services",
      "Iberian Data Operations",
      "Lisbon Business Support",
      "Tagus Data Group",
      "Porto Data Solutions",
      "Coastal Records Services",
      "Portugal DataWorks",
      "Sintra Data Operations",
      "Madeira Desk Solutions",
      "Algarve Data Services",
      "LisbonPoint Administration",
      "Iberia Records Group",
      "Atlantic Desk Operations",
      "Portuguese Data Support",
      "Porto Business Records",
      "Tagus Data Solutions",
      "Portugal Digital Services",
      "Lisbon Records Group",
      "Iberian Desk Solutions",
    ],
    positions: [
      "Data Entry Clerk",
      "Data Processing Assistant",
      "Remote Data Entry Specialist",
      "Records Data Assistant",
      "Online Data Clerk",
      "Administrative Data Specialist",
      "Data Verification Assistant",
      "Database Entry Specialist",
      "Digital Records Clerk",
      "Data Input Assistant",
      "Information Processing Clerk",
      "Data Management Specialist",
      "Document Data Assistant",
      "Data Quality Clerk",
      "Remote Records Specialist",
      "Data Operations Assistant",
      "Customer Data Clerk",
      "Data Administration Specialist",
      "Data Capture Assistant",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Back Office Data Assistant",
    ],
  },
  {
    country: "Brazil",
    companies: [
      "Brazil Data Solutions",
      "Rio Data Services",
      "Sao Paulo Desk Operations",
      "Amazon Data Group",
      "Verde Records Services",
      "BrazilCore Administration",
      "Brasilia Data Solutions",
      "Bahia Data Operations",
      "Curitiba Records Group",
      "Recife Data Services",
      "Atlantic Brazil Support",
      "Samba Data Solutions",
      "Amazonia Desk Group",
      "RioPoint Data Services",
      "Brazil Business Records",
      "Paulista Data Operations",
      "Verde Data Management",
      "Brazil Records Solutions",
      "Coastal Data Group",
      "Tropical Desk Services",
      "Brazil DataWorks",
      "Atlantic Records Brazil",
      "SaoPaulo Data Support",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Specialist",
      "Online Data Entry Clerk",
      "Administrative Data Assistant",
      "Data Verification Specialist",
      "Database Entry Assistant",
      "Digital Records Specialist",
      "Data Input Clerk",
      "Information Processing Assistant",
      "Data Management Specialist",
      "Document Data Clerk",
      "Data Quality Assistant",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Customer Data Specialist",
      "Data Administration Clerk",
      "Data Capture Specialist",
      "Business Data Assistant",
      "Entry-Level Data Clerk",
      "Back Office Data Specialist",
      "Document Processing Assistant",
    ],
  },
  {
    country: "China",
    companies: [
      "Dragon Data Services",
      "China Data Solutions",
      "Beijing Desk Operations",
      "Shanghai Data Group",
      "Pearl River Records",
      "GreatWall Data Services",
      "Shenzhen Data Solutions",
      "Guangzhou Records Group",
      "Eastern Data Operations",
      "Beijing Business Support",
      "Shanghai Desk Services",
      "ChinaCore Data Group",
      "Jade Records Solutions",
      "SilkRoad Data Services",
      "DragonPoint Operations",
      "Pacific China Data",
      "Eastern Records Group",
      "China Digital Services",
      "Pearl Data Operations",
      "JadeDesk Solutions",
      "Beijing Data Management",
      "China DataWorks",
      "GreatWall Records Services",
    ],
    positions: [
      "Data Entry Clerk",
      "Remote Data Assistant",
      "Data Processing Specialist",
      "Records Data Clerk",
      "Online Data Entry Assistant",
      "Administrative Data Specialist",
      "Data Verification Clerk",
      "Database Entry Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Data Specialist",
      "Data Quality Assistant",
      "Remote Records Specialist",
      "Data Operations Clerk",
      "Customer Data Assistant",
      "Data Administration Specialist",
      "Data Capture Clerk",
      "Business Data Specialist",
      "Entry-Level Data Clerk",
      "Back Office Data Assistant",
      "Document Processing Specialist",
    ],
  },
  {
    country: "UAE",
    companies: [
      "Emirates Data Services",
      "Dubai Desk Solutions",
      "GulfPoint Data Group",
      "Abu Dhabi Records",
      "Desert Data Operations",
      "Falcon Business Support",
      "Emirates Data Solutions",
      "Dubai Records Services",
      "Capital Data Group",
      "GulfCore Administration",
      "Pearl Data Services",
      "DubaiPoint Operations",
      "Arabian Data Solutions",
      "UAE Records Group",
      "Oasis Data Services",
      "Gulf Digital Records",
      "Emirates Desk Operations",
      "DesertPoint Data",
      "Dubai Business Records",
      "Abu Dhabi Data Services",
      "Falcon Data Operations",
      "Gulf Records Solutions",
      "Emirates DataWorks",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Clerk",
      "Online Data Specialist",
      "Administrative Data Assistant",
      "Data Verification Specialist",
      "Database Entry Clerk",
      "Digital Records Assistant",
      "Data Input Specialist",
      "Information Processing Clerk",
      "Data Management Assistant",
      "Document Data Specialist",
      "Data Quality Clerk",
      "Remote Records Assistant",
      "Data Operations Specialist",
      "Customer Data Clerk",
      "Data Administration Assistant",
      "Data Capture Specialist",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Back Office Data Assistant",
      "Document Processing Clerk",
    ],
  },
  {
    country: "Japan",
    companies: [
      "Tokyo Data Services",
      "Nippon Data Solutions",
      "Sakura Desk Operations",
      "Osaka Records Group",
      "Fuji Data Services",
      "Kyoto Data Solutions",
      "Pacific Records Japan",
      "TokyoPoint Administration",
      "Shibuya Data Operations",
      "Nara Business Support",
      "Hikari Data Group",
      "Sakura Records Services",
      "Nippon Desk Solutions",
      "FujiPoint Data",
      "Osaka Data Operations",
      "Tokyo Records Management",
      "Japan Digital Services",
      "Kyoto Data Group",
      "Pacific Desk Japan",
      "Sakura DataWorks",
      "Nippon Records Solutions",
      "Tokyo Business Data",
      "Fuji Records Services",
    ],
    positions: [
      "Data Entry Clerk",
      "Data Processing Assistant",
      "Remote Data Specialist",
      "Records Data Assistant",
      "Online Data Entry Clerk",
      "Administrative Data Specialist",
      "Data Verification Assistant",
      "Database Entry Specialist",
      "Digital Records Clerk",
      "Data Input Assistant",
      "Information Processing Specialist",
      "Data Management Clerk",
      "Document Data Assistant",
      "Data Quality Specialist",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Customer Data Specialist",
      "Data Administration Clerk",
      "Data Capture Assistant",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Back Office Data Assistant",
      "Document Processing Specialist",
    ],
  },
  {
    country: "Turkey",
    companies: [
      "Istanbul Data Services",
      "Anatolia Data Solutions",
      "Bosphorus Desk Operations",
      "Turkey Records Group",
      "Crescent Data Services",
      "Ankara Data Solutions",
      "Izmir Records Services",
      "Turkish Data Operations",
      "Istanbul Business Support",
      "Cappadocia Data Group",
      "Marmara Desk Services",
      "Anatolian Records Solutions",
      "Bosphorus Data Group",
      "Turkey DataWorks",
      "IstanbulPoint Operations",
      "Turkish Digital Services",
      "Crescent Records Group",
      "Ankara Data Services",
      "Aegean Data Solutions",
      "Turkey Business Records",
      "Marmara Data Operations",
      "Anatolia Desk Group",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Clerk",
      "Online Data Entry Specialist",
      "Administrative Data Assistant",
      "Data Verification Clerk",
      "Database Entry Assistant",
      "Digital Records Specialist",
      "Data Input Clerk",
      "Information Processing Assistant",
      "Data Management Specialist",
      "Document Data Clerk",
      "Data Quality Assistant",
      "Remote Records Specialist",
      "Data Operations Clerk",
      "Customer Data Assistant",
      "Data Administration Specialist",
      "Data Capture Clerk",
      "Business Data Specialist",
      "Entry-Level Data Clerk",
      "Back Office Data Assistant",
    ],
  },
  {
    country: "South Korea",
    companies: [
      "Seoul Data Services",
      "Korea Data Solutions",
      "Han River Operations",
      "Seoul Records Group",
      "Korean Desk Services",
      "Busan Data Solutions",
      "Incheon Records Group",
      "KoreaCore Data Services",
      "SeoulPoint Operations",
      "Han Data Management",
      "Daegu Data Services",
      "Jeju Records Solutions",
      "Korean Digital Services",
      "Seoul Business Support",
      "Pacific Korea Data",
      "HanRiver Data Group",
      "Korea Records Operations",
      "Seoul DataWorks",
      "Busan Desk Solutions",
      "Korean Data Management",
      "Incheon Data Services",
      "Seoul Records Solutions",
    ],
    positions: [
      "Data Entry Clerk",
      "Remote Data Assistant",
      "Data Processing Specialist",
      "Records Data Clerk",
      "Online Data Entry Assistant",
      "Administrative Data Specialist",
      "Data Verification Clerk",
      "Database Entry Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Data Specialist",
      "Data Quality Assistant",
      "Remote Records Specialist",
      "Data Operations Clerk",
      "Customer Data Assistant",
      "Data Administration Specialist",
      "Data Capture Clerk",
      "Business Data Specialist",
      "Entry-Level Data Clerk",
      "Back Office Data Assistant",
    ],
  },
  {
    country: "Indonesia",
    companies: [
      "Jakarta Data Services",
      "Indo Data Solutions",
      "Nusantara Desk Operations",
      "Bali Records Group",
      "Java Data Services",
      "Jakarta Data Solutions",
      "Island Records Operations",
      "Garuda Data Group",
      "Surabaya Desk Services",
      "Bandung Data Solutions",
      "IndoCore Administration",
      "Nusantara Records Services",
      "JakartaPoint Data",
      "Bali Data Operations",
      "Java Records Group",
      "Indonesia Digital Services",
      "Garuda Desk Solutions",
      "Island Data Management",
      "Jakarta Business Records",
      "Indo DataWorks",
      "Nusantara Data Services",
      "Surabaya Records Solutions",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Specialist",
      "Online Data Entry Clerk",
      "Administrative Data Assistant",
      "Data Verification Specialist",
      "Database Entry Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Specialist",
      "Document Data Clerk",
      "Data Quality Assistant",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Customer Data Specialist",
      "Data Administration Clerk",
      "Data Capture Specialist",
      "Business Data Assistant",
      "Entry-Level Data Clerk",
      "Back Office Data Specialist",
    ],
  },
  {
    country: "Austria",
    companies: [
      "Vienna Data Services",
      "Alpine Data Solutions",
      "Austria Desk Operations",
      "Danube Records Group",
      "Vienna Business Support",
      "Tyrol Data Services",
      "Salzburg Data Solutions",
      "Austrian Records Group",
      "Graz Data Operations",
      "Alpine Desk Services",
      "ViennaPoint Administration",
      "Danube Data Group",
      "Austria Digital Services",
      "Imperial Data Solutions",
      "Tyrol Records Services",
      "Central Europe Data",
      "Vienna DataWorks",
      "Alpine Records Operations",
      "Austrian Data Management",
      "Danube Desk Solutions",
      "Graz Records Group",
      "Salzburg Data Services",
    ],
    positions: [
      "Data Entry Clerk",
      "Data Processing Specialist",
      "Remote Data Assistant",
      "Records Data Clerk",
      "Online Data Entry Specialist",
      "Administrative Data Assistant",
      "Data Verification Clerk",
      "Database Entry Specialist",
      "Digital Records Assistant",
      "Data Input Clerk",
      "Information Processing Specialist",
      "Data Management Clerk",
      "Document Data Assistant",
      "Data Quality Specialist",
      "Remote Records Clerk",
      "Data Operations Specialist",
      "Customer Data Assistant",
      "Data Administration Clerk",
      "Data Capture Specialist",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
      "Back Office Data Assistant",
    ],
  },
  {
    country: "Nigeria",
    companies: [
      "Lagos Data Services",
      "Naija Data Solutions",
      "West Africa Desk Operations",
      "Nigerian Records Group",
      "Lagos Digital Support",
      "Abuja Data Services",
      "NaijaCore Operations",
      "Port Harcourt Data Solutions",
      "Ibadan Records Group",
      "Kano Data Services",
      "LagosPoint Administration",
      "GreenAfrica Data Solutions",
      "Nigerian Desk Services",
      "WestPoint Data Operations",
      "Naija Records Solutions",
      "Africa DataWorks",
      "Lagos Business Records",
      "Abuja Data Operations",
      "Nigerian Digital Services",
      "Coastal Data Group",
      "Naija Data Management",
      "West Africa Records Services",
      "Lagos Data Operations",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Online Data Entry Specialist",
      "Records Data Clerk",
      "Administrative Data Assistant",
      "Data Verification Specialist",
      "Database Entry Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Data Specialist",
      "Data Quality Assistant",
      "Remote Records Specialist",
      "Data Operations Assistant",
      "Customer Data Clerk",
      "Data Administration Specialist",
      "Data Capture Assistant",
      "Business Data Specialist",
      "Entry-Level Data Clerk",
      "Back Office Data Assistant",
      "Document Processing Clerk",
    ],
  },
  {
    country: "Oman",
    companies: [
      "Oman Data Services",
      "Muscat Data Solutions",
      "Gulf Desk Operations",
      "Oman Records Group",
      "Muscat Business Support",
      "Arabian Data Services",
      "OmanCore Operations",
      "Salalah Data Solutions",
      "Muscat Records Services",
      "GulfPoint Data Group",
      "Oman Digital Services",
      "Desert Records Solutions",
      "MuscatPoint Administration",
      "Oman Data Operations",
      "Arabian Records Group",
      "Gulf Data Management",
      "Oman Desk Solutions",
      "Muscat DataWorks",
      "Coastal Oman Services",
      "Oman Business Records",
      "Gulf Records Operations",
      "Arabian Data Solutions",
    ],
    positions: [
      "Data Entry Clerk",
      "Remote Data Processing Assistant",
      "Data Entry Specialist",
      "Records Data Assistant",
      "Online Data Clerk",
      "Administrative Data Specialist",
      "Data Verification Assistant",
      "Database Entry Clerk",
      "Digital Records Specialist",
      "Data Input Assistant",
      "Information Processing Clerk",
      "Data Management Specialist",
      "Document Data Assistant",
      "Data Quality Clerk",
      "Remote Records Specialist",
      "Data Operations Clerk",
      "Customer Data Assistant",
      "Data Administration Specialist",
      "Data Capture Clerk",
      "Business Data Specialist",
      "Entry-Level Data Assistant",
      "Back Office Data Clerk",
    ],
  },
  {
    country: "Jordan",
    companies: [
      "Amman Data Services",
      "Jordan Data Solutions",
      "Levant Desk Operations",
      "Jordan Records Group",
      "Amman Business Support",
      "Petra Data Services",
      "JordanCore Operations",
      "Aqaba Data Solutions",
      "Amman Records Services",
      "Levant Data Group",
      "Jordan Digital Services",
      "Petra Records Solutions",
      "AmmanPoint Administration",
      "Jordan Data Operations",
      "Levant Records Group",
      "Jordan Data Management",
      "Amman Desk Solutions",
      "Petra DataWorks",
      "Jordan Business Records",
      "Aqaba Data Operations",
      "Levant Data Services",
    ],
    positions: [
      "Data Entry Specialist",
      "Remote Data Entry Clerk",
      "Data Processing Assistant",
      "Records Data Clerk",
      "Online Data Entry Assistant",
      "Administrative Data Specialist",
      "Data Verification Clerk",
      "Database Entry Assistant",
      "Digital Records Clerk",
      "Data Input Specialist",
      "Information Processing Assistant",
      "Data Management Clerk",
      "Document Data Specialist",
      "Data Quality Assistant",
      "Remote Records Clerk",
      "Data Operations Specialist",
      "Customer Data Assistant",
      "Data Administration Clerk",
      "Data Capture Specialist",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
    ],
  },
  {
    country: "Bahrain",
    companies: [
      "Bahrain Data Services",
      "Manama Data Solutions",
      "Gulf Desk Operations",
      "Bahrain Records Group",
      "Manama Business Support",
      "Pearl Data Services",
      "BahrainCore Operations",
      "GulfPoint Data Solutions",
      "Manama Records Services",
      "Arabian Data Group",
      "Bahrain Digital Services",
      "Pearl Records Solutions",
      "ManamaPoint Administration",
      "Bahrain Data Operations",
      "Gulf Records Group",
      "Bahrain Data Management",
      "Manama Desk Solutions",
      "Pearl DataWorks",
      "Bahrain Business Records",
      "Gulf Data Operations",
      "Arabian Data Services",
    ],
    positions: [
      "Data Entry Clerk",
      "Remote Data Assistant",
      "Data Processing Specialist",
      "Records Data Clerk",
      "Online Data Entry Specialist",
      "Administrative Data Assistant",
      "Data Verification Clerk",
      "Database Entry Specialist",
      "Digital Records Assistant",
      "Data Input Clerk",
      "Information Processing Specialist",
      "Data Management Clerk",
      "Document Data Assistant",
      "Data Quality Specialist",
      "Remote Records Clerk",
      "Data Operations Assistant",
      "Customer Data Specialist",
      "Data Administration Clerk",
      "Data Capture Assistant",
      "Business Data Clerk",
      "Entry-Level Data Specialist",
    ],
  },
];
/*
 * Build the hardcoded job records.
 *
 * The company arrays above contain 500 unique company names.
 * Positions are rotated so each listing has a data-entry-related
 * opening title.
 */
const dataEntryJobs: DataEntryJob[] = countries.flatMap(
  ({ country, companies, positions }) =>
    companies.map((company, index) => ({
      company,
      location: country,
      position: positions[index % positions.length],
      status: "active",
    })),
);


export async function GET() {
  const shuffledJobs = [...dataEntryJobs];
  // Fisher-Yates shuffle
  for (let index = shuffledJobs.length - 1; index > 0; index--) {
    const randomIndex = Math.floor(Math.random() * (index + 1));
    [shuffledJobs[index], shuffledJobs[randomIndex]] = [
      shuffledJobs[randomIndex],
      shuffledJobs[index],
    ];
  }
  const selectedJobs = shuffledJobs.slice(0, 60);
  return NextResponse.json({
    total: dataEntryJobs.length,
    returned: selectedJobs.length,
    jobs: selectedJobs,
  });
}